#数据源
spring:
  redis:
    host: 121.5.246.216
    port: 6379
    database: 0
    password: "catchers.tech"

#    url: redis://catchers.tech@121.5.246.216:6379/0
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  devtools:
    restart:
      additional-paths: src/main/java
logging:
  level:
    root: info
    com.dnslin.dnslin_api: debug
server:
  port: 5678
